export const ADD_TODO = 'ADD_TODO';

// Login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

// Signup
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

// Logout
export const LOGOUT = 'LOGOUT';

// Modal
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

// Master table

export const MASTER_TABLE_FETCH_REQUEST = 'MASTER_TABLE_FETCH_REQUEST';
export const MASTER_TABLE_FETCH_SUCCESS = 'MASTER_TABLE_FETCH_SUCCESS';
export const MASTER_TABLE_FETCH_FAILURE = 'MASTER_TABLE_FETCH_FAILURE';

// Profile
export const PROFILE_FETCH_REQUEST = 'PROFILE_FETCH_REQUEST';
export const PROFILE_FETCH_SUCCESS = 'PROFILE_FETCH_SUCCESS';
export const PROFILE_FETCH_FAILURE = 'PROFILE_FETCH_FAILURE';
export const PROFILE_UPDATE_REQUEST = 'PROFILE_UPDATE_REQUEST';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const PROFILE_UPDATE_FAILURE = 'PROFILE_UPDATE_FAILURE';
export const PROFILE_DELETE_REQUEST = 'PROFILE_DELETE_REQUEST';
export const PROFILE_DELETE_SUCCESS = 'PROFILE_DELETE_SUCCESS';
export const PROFILE_DELETE_FAILURE = 'PROFILE_DELETE_FAILURE';

// Employee
export const EMPLOYEE_CREATE_REQUEST = 'EMPLOYEE_CREATE_REQUEST';
export const EMPLOYEE_CREATE_SUCCESS = 'EMPLOYEE_CREATE_SUCCESS';
export const EMPLOYEE_CREATE_FAILURE = 'EMPLOYEE_CREATE_FAILURE';
export const EMPLOYEE_FETCH_REQUEST = 'EMPLOYEE_FETCH_REQUEST';
export const EMPLOYEE_FETCH_SUCCESS = 'EMPLOYEE_FETCH_SUCCESS';
export const EMPLOYEE_FETCH_FAILURE = 'EMPLOYEE_FETCH_FAILURE';
export const FILTER_EMPLOYEE = 'FILTER_EMPLOYEE';

// Project
export const PROJECT_CREATE_REQUEST = 'PROJECT_CREATE_REQUEST';
export const PROJECT_CREATE_SUCCESS = 'PROJECT_CREATE_SUCCESS';
export const PROJECT_CREATE_FAILURE = 'PROJECT_CREATE_FAILURE';
export const PROJECT_FETCH_REQUEST = 'PROJECT_FETCH_REQUEST';
export const PROJECT_FETCH_SUCCESS = 'PROJECT_FETCH_SUCCESS';
export const PROJECT_FETCH_FAILURE = 'PROJECT_FETCH_FAILURE';
export const FILTER_PROJECT = 'FILTER_PROJECT';
export const SORT_PROJECT = 'SORT_PROJECT';

// Project detail
export const PROJECT_DETAIL_FETCH_REQUEST = 'PROJECT_DETAIL_FETCH_REQUEST';
export const PROJECT_DETAIL_FETCH_SUCCESS = 'PROJECT_DETAIL_FETCH_SUCCESS';
export const PROJECT_DETAIL_FETCH_FAILURE = 'PROJECT_DETAIL_FETCH_FAILURE';

// Leave
export const LEAVE_CREATE_REQUEST = 'LEAVE_CREATE_REQUEST';
export const LEAVE_CREATE_SUCCESS = 'LEAVE_CREATE_SUCCESS';
export const LEAVE_CREATE_FAILURE = 'LEAVE_CREATE_FAILURE';
export const LEAVE_FETCH_REQUEST = 'LEAVE_FETCH_REQUEST';
export const LEAVE_FETCH_SUCCESS = 'LEAVE_FETCH_SUCCESS';
export const LEAVE_FETCH_FAILURE = 'LEAVE_FETCH_FAILURE';
export const LEAVE_UPDATE_REQUEST = 'LEAVE_UPDATE_REQUEST';
export const LEAVE_UPDATE_SUCCESS = 'LEAVE_UPDATE_SUCCESS';
export const LEAVE_UPDATE_FAILURE = 'LEAVE_UPDATE_FAILURE';
export const FILTER_LEAVE = 'FILTER_LEAVE';

// Timesheet
export const TIMESHEET_FETCH_REQUEST = 'TIMESHEET_FETCH_REQUEST';
export const TIMESHHET_FETCH_SUCCESS = 'TIMESHHET_FETCH_SUCCESS';
export const TIMESHHET_FETCH_FAILURE = 'TIMESHHET_FETCH_FAILURE';

// exam
export const ADD_EXAM_REQUEST = 'ADD_EXAM_REQUEST';
export const ADD_EXAM_SUCCESS = 'ADD_EXAM_SUCCESS';
export const ADD_EXAM_FAILURE = 'ADD_EXAM_FAILURE';
export const EXAM_FETCH_REQUEST = 'EXAM_FETCH_REQUEST';
export const EXAM_FETCH_SUCCESS = 'EXAM_FETCH_SUCCESS';
export const EXAM_FETCH_FAILURE = 'EXAM_FETCH_FAILURE';
export const FILTER_EXAMS = 'FILTER_EXAMS';
export const DELETE_EXAM_REQUEST = 'DELETE_EXAM_REQUEST';
export const DELETE_EXAM_SUCCESS = 'DELETE_EXAM_SUCCESS';
export const DELETE_EXAM_FAILURE = 'DELETE_EXAM_FAILURE';
export const EDIT_EXAM_REQUEST = 'EDIT_EXAM_REQUEST';
export const EDIT_EXAM_SUCCESS = 'EDIT_EXAM_SUCCESS';
export const EDIT_EXAM_FAILURE = 'EDIT_EXAM_FAILURE';

// recruitment
export const RECRUITMENT_CHANGE_ACTIVE_ITEM = 'RECRUITMENT_CHANGE_ACTIVE_ITEM';
export const RECRUITMENT_FETCH_REQUEST = 'RECRUITMENT_FETCH_REQUEST';
export const RECRUITMENT_FETCH_SUCCESS = 'RECRUITMENT_FETCH_SUCCESS';
export const RECRUITMENT_FETCH_FAILURE = 'RECRUITMENT_FETCH_FAILURE';
export const RECRUITMENT_FETCH_POSITION_REQUEST = 'RECRUITMENT_FETCH_POSITION_REQUEST';
export const RECRUITMENT_FETCH_POSITION_SUCCESS = 'RECRUITMENT_FETCH_POSITION_SUCCESS';
export const RECRUITMENT_FETCH_POSITION_FAILURE = 'RECRUITMENT_FETCH_POSITION_FAILURE';
export const FILTER_RECRUITMENT = 'FILTER_RECRUITMENT';
export const SORT_RECRUITMENT = 'SORT_RECRUITMENT';
export const CHECK_RECRUITMENT_STATUS = 'CHECK_RECRUITMENT_STATUS';
export const CHANGE_RECRUITMENT_STATUS = 'CHANGE_RECRUITMENT_STATUS';
export const CLEAR_CHECKSTATUS = 'CLEAR_CHECKSTATUS';
export const CLEAR_DATETIME = 'CLEAR_DATETIME';
export const CLEAR_POSITION = 'CLEAR_POSITION';
export const RECRUITMENT_CREATE_REQUEST = 'RECRUITMENT_CREATE_REQUEST';
export const RECRUITMENT_CREATE_SUCCESS = 'RECRUITMENT_CREATE_SUCCESS';
export const RECRUITMENT_CREATE_FAILURE = 'RECRUITMENT_CREATE_FAILURE';
export const RECRUITMENT_SETDATE = 'RECRUITMENT_SETDATE';
export const RECRUITMENT_SET_SELECT_POSITION = 'RECRUITMENT_SET_SELECT_POSITION';
export const RECRUITMENT_SETTIME = 'RECRUITMENT_SETTIME';
export const RECRUITMENT_UPDATE_SIGNED_POSITION_REQUEST = 'RECRUITMENT_UPDATE_SIGNED_POSITION_REQUEST';
export const RECRUITMENT_UPDATE_SIGNED_POSITION_SUCCESS = 'RECRUITMENT_UPDATE_SIGNED_POSITION_SUCCESS';
export const RECRUITMENT_UPDATE_SIGNED_POSITION_FAILURE = 'RECRUITMENT_UPDATE_SIGNED_POSITION_FAILURE';
export const RECRUITMENT_UPDATE_INTERVIEW_DATETIME_REQUEST = 'RECRUITMENT_UPDATE_INTERVIEW_DATETIME_REQUEST';
export const RECRUITMENT_UPDATE_INTERVIEW_DATETIME_SUCCESS = 'RECRUITMENT_UPDATE_INTERVIEW_DATETIME_SUCCESS';
export const RECRUITMENT_UPDATE_INTERVIEW_DATETIME_FAILURE = 'RECRUITMENT_UPDATE_INTERVIEW_DATETIME_FAILURE';
export const RECRUITMENT_UPDATE_EXAM_DATETIME_REQUEST = 'RECRUITMENT_UPDATE_EXAM_DATETIME_REQUEST';
export const RECRUITMENT_UPDATE_EXAM_DATETIME_SUCCESS = 'RECRUITMENT_UPDATE_EXAM_DATETIME_SUCCESS';
export const RECRUITMENT_UPDATE_EXAM_DATETIME_FAILURE = 'RECRUITMENT_UPDATE_EXAM_DATETIME_FAILURE';
export const RECRUITMENT_UPDATE_SIGN_DATETIME_REQUEST = 'RECRUITMENT_UPDATE_SIGN_DATETIME_REQUEST';
export const RECRUITMENT_UPDATE_SIGN_DATETIME_SUCCESS = 'RECRUITMENT_UPDATE_SIGN_DATETIME_SUCCESS';
export const RECRUITMENT_UPDATE_SIGN_DATETIME_FAILURE = 'RECRUITMENT_UPDATE_SIGN_DATETIME_FAILURE';
export const RECRUITMENT_UPDATE_COMPLETE_DATETIME_REQUEST = 'RECRUITMENT_UPDATE_COMPLETE_DATETIME_REQUEST';
export const RECRUITMENT_UPDATE_COMPLETE_DATETIME_SUCCESS = 'RECRUITMENT_UPDATE_COMPLETE_DATETIME_SUCCESS';
export const RECRUITMENT_UPDATE_COMPLETE_DATETIME_FAILURE = 'RECRUITMENT_UPDATE_COMPLETE_DATETIME_FAILURE';
export const RECRUITMENT_UPDATE_REJECT_DATE_REQUEST = 'RECRUITMENT_UPDATE_REJECT_DATE_REQUEST';
export const RECRUITMENT_UPDATE_REJECT_DATE_SUCCESS = 'RECRUITMENT_UPDATE_REJECT_DATE_SUCCESS';
export const RECRUITMENT_UPDATE_REJECT_DATE_FAILURE = 'RECRUITMENT_UPDATE_REJECT_DATE_FAILURE';
export const RECRUITMENT_UPDATE_CANCEL_DATE_REQUEST = 'RECRUITMENT_UPDATE_CANCEL_DATE_REQUEST';
export const RECRUITMENT_UPDATE_CANCEL_DATE_SUCCESS = 'RECRUITMENT_UPDATE_CANCEL_DATE_SUCCESS';
export const RECRUITMENT_UPDATE_CANCEL_DATE_FAILURE = 'RECRUITMENT_UPDATE_CANCEL_DATE_FAILURE';
export const RECRUITMENT_UPDATE_BLACKLIST_DATE_REQUEST = 'RECRUITMENT_UPDATE_BLACKLIST_DATE_REQUEST';
export const RECRUITMENT_UPDATE_BLACKLIST_DATE_SUCCESS = 'RECRUITMENT_UPDATE_BLACKLIST_DATE_SUCCESS';
export const RECRUITMENT_UPDATE_BLACKLIST_DATE_FAILURE = 'RECRUITMENT_UPDATE_BLACKLIST_DATE_FAILURE';
export const RECRUITMENT_UPDATE_NOTE_REQUEST = 'RECRUITMENT_UPDATE_NOTE_REQUEST';
export const RECRUITMENT_UPDATE_NOTE_SUCCESS = 'RECRUITMENT_UPDATE_NOTE_SUCCESS';
export const RECRUITMENT_UPDATE_NOTE_FAILURE = 'RECRUITMENT_UPDATE_NOTE_FAILURE';
export const RECRUITMENT_UPDATE_INTERVIEW_RESULT_REQUEST = 'RECRUITMENT_UPDATE_INTERVIEW_RESULT_REQUEST';
export const RECRUITMENT_UPDATE_INTERVIEW_RESULT_SUCCESS = 'RECRUITMENT_UPDATE_INTERVIEW_RESULT_SUCCESS';
export const RECRUITMENT_UPDATE_INTERVIEW_RESULT_FAILURE = 'RECRUITMENT_UPDATE_INTERVIEW_RESULT_FAILURE';
export const RECRUITMENT_PRE_ACTIVATE_TAKE_EXAM_REQUEST = 'RECRUITMENT_PRE_ACTIVATE_TAKE_EXAM_REQUEST';
export const RECRUITMENT_SET_UP_MODAL = 'RECRUITMENT_SET_UP_MODAL';
export const RECRUITMENT_SET_UP_MODAL_COMPLETE = 'RECRUITMENT_SET_UP_MODAL_COMPLETE';
export const RECRUITMENT_ACTIVATE_EXAM_USER_REQUEST = 'RECRUITMENT_ACTIVATE_EXAM_USER_REQUEST';
export const RECRUITMENT_ACTIVATE_EXAM_USER_SUCCESS = 'RECRUITMENT_ACTIVATE_EXAM_USER_SUCCESS';
export const RECRUITMENT_ACTIVATE_EXAM_USER_FAILURE = 'RECRUITMENT_ACTIVATE_EXAM_USER_FAILURE';
export const RECRUITMENT_FETCH_TEST_STATUS_REQUEST = 'RECRUITMENT_FETCH_TEST_STATUS_REQUEST';
export const RECRUITMENT_FETCH_TEST_STATUS_RESPONSE = 'RECRUITMENT_FETCH_TEST_STATUS_RESPONSE';
export const CHANGE_INTERVIEW_STATUS_REQUEST = 'CHANGE_INTERVIEW_STATUS_REQUEST';
export const CHANGE_INTERVIEW_STATUS_RESPONSE = 'CHANGE_INTERVIEW_STATUS_RESPONSE';
export const RECRUITMENT_RANDOM_EXAM = 'RECRUITMENT_RANDOM_EXAM';
export const RECRUITMENT_CHANGE_WARNING_SCORE = 'RECRUITMENT_CHANGE_WARNING_SCORE';
export const RECRUITMENT_CHANGE_WARNING_FULLSCORE = 'RECRUITMENT_CHANGE_WARNING_FULLSCORE';

// Recruitment : Grading
export const RECRUITMENT_GRADING_FETCH_REQUEST = 'RECRUITMENT_GRADING_FETCH_REQUEST';
export const RECRUITMENT_GRADING_FETCH_FAILURE = 'RECRUITMENT_GRADING_FETCH_FAILURE';
export const RECRUITMENT_GRADING_FETCH_SUCCESS = 'RECRUITMENT_GRADING_FETCH_SUCCESS';
export const GRADING_MODAL_PAGINATION_CHANGE = 'GRADING_MODAL_PAGINATION_CHANGE';
export const GRADING_MODAL_CATEGORY_CHANGE = 'GRADING_MODAL_CATEGORY_CHANGE';
export const GRADING_MODAL_ON_INPUT_COMMENT = 'GRADING_MODAL_ON_INPUT_COMMENT';
export const GRADING_MODAL_ON_SCORE_CHANGE = 'GRADING_MODAL_ON_SCORE_CHANGE';
export const GRADING_MODAL_ON_FULLSCORE_CHANGE = 'GRADING_MODAL_ON_FULLSCORE_CHANGE';
export const GRADING_MODAL_SAVE_REQUEST = 'GRADING_MODAL_SAVE_REQUEST';
export const GRADING_MODAL_SAVE_FAILURE = 'GRADING_MODAL_SAVE_FAILURE';
export const GRADING_MODAL_SAVE_SUCCESS = 'GRADING_MODAL_SAVE_SUCCESS';
export const GRADING_MODAL_SEND_REQUEST = 'GRADING_MODAL_SEND_REQUEST';
export const GRADING_MODAL_SEND_FAILURE = 'GRADING_MODAL_SEND_FAILURE';
export const GRADING_MODAL_SEND_SUCCESS = 'GRADING_MODAL_SEND_SUCCESS';
export const GRADING_MODAL_SCORE_HANDLE = 'GRADING_MODAL_SCORE_HANDLE';
export const GRADING_MODAL_SCORE_PUSHBACK = 'GRADING_MODAL_SCORE_PUSHBACK';

// recruitment profile
export const RECRUITMENT_PROFILE_FETCH_REQUEST = 'RECRUITMENT_PROFILE_FETCH_REQUEST';
export const RECRUITMENT_PROFILE_FETCH_SUCCESS = 'RECRUITMENT_PROFILE_FETCH_SUCCESS';
export const RECRUITMENT_PROFILE_FETCH_FAILURE = 'RECRUITMENT_PROFILE_FETCH_FAILURE';

// exam login
export const EXAM_LOGIN_REQUEST = 'EXAM_LOGIN_REQUEST';
export const EXAM_LOGIN_SUCCESS = 'EXAM_LOGIN_SUCCESS';
export const EXAM_LOGIN_FAILURE = 'EXAM_LOGIN_FAILURE';
export const EXAM_LOGOUT = 'EXAM_LOGOUT';

// prepare to exam
export const FETCH_EXAM_LIST_REQUEST = 'FETCH_EXAM_LIST_REQUEST';

// take exam agreement
export const TAKE_EXAM_AGREEMENT_CLICK_CHECKBOX = 'TAKE_EXAM_AGREEMENT_CLICK_CHECKBOX';
export const TAKE_EXAM_AGREEMENT_START_EXAM_REQUEST = 'TAKE_EXAM_AGREEMENT_START_EXAM_REQUEST';
export const TAKE_EXAM_AGREEMENT_START_EXAM_FAILURE = 'TAKE_EXAM_AGREEMENT_START_EXAM_FAILURE';
export const TAKE_EXAM_AGREEMENT_START_EXAM_SUCCESS = 'TAKE_EXAM_AGREEMENT_START_EXAM_SUCCESS';

// take exam
export const TAKE_EXAM_FETCH_REQUEST = 'TAKE_EXAM_FETCH_REQUEST';
export const TAKE_EXAM_FETCH_FAILURE = 'TAKE_EXAM_FETCH_FAILURE';
export const TAKE_EXAM_FETCH_SUCCESS = 'TAKE_EXAM_FETCH_SUCCESS';
export const TAKE_EXAM_FETCH_PROGRESS = 'TAKE_EXAM_FETCH_PROGRESS';
export const TAKE_EXAM_FETCH_CATEGORYLIST = 'TAKE_EXAM_FETCH_CATEGORYLIST';
export const TAKE_EXAM_FETCH_SUB_CATEGORYLIST = 'TAKE_EXAM_FETCH_SUB_CATEGORYLIST';
export const TAKE_EXAM_PAGINATION_CHANGE = 'TAKE_EXAM_PAGINATION_CHANGE';
export const TAKE_EXAM_SAVE_ANSWERLIST = 'TAKE_EXAM_SAVE_ANSWERLIST';
export const TAKE_EXAM_ON_PICK_RADIO = 'TAKE_EXAM_ON_PICK_RADIO';
export const TAKE_EXAM_ON_PICK_CHECKBOX = 'TAKE_EXAM_ON_PICK_CHECKBOX';
export const TAKE_EXAM_ON_INPUT_TEXTAREA = 'TAKE_EXAM_ON_INPUT_TEXTAREA';
export const TAKE_EXAM_UPLOAD_REQUEST = 'TAKE_EXAM_UPLOAD_REQUEST';
export const TAKE_EXAM_UPLOAD_FAILURE = 'TAKE_EXAM_UPLOAD_FAILURE';
export const TAKE_EXAM_UPLOAD_SUCCESS = 'TAKE_EXAM_UPLOAD_SUCCESS';
export const TAKE_EXAM_CHECK_PROGRESS_REQUEST = 'TAKE_EXAM_CHECK_PROGRESS_REQUEST';
export const TAKE_EXAM_CHECK_PROGRESS_FAILURE = 'TAKE_EXAM_CHECK_PROGRESS_FAILURE';
export const TAKE_EXAM_CHECK_PROGRESS_SUCCESS = 'TAKE_EXAM_CHECK_PROGRESS_SUCCESS';
export const TAKE_EXAM_CATEGORY_CHANGE = 'TAKE_EXAM_CATEGORY_CHANGE';
export const TAKE_EXAM_FINISH_EXAM_REQUEST = 'TAKE_EXAM_FINISH_EXAM_REQUEST';
export const TAKE_EXAM_FINISH_EXAM_FAILURE = 'TAKE_EXAM_FINISH_EXAM_FAILURE';
export const TAKE_EXAM_FINISH_EXAM_SUCCESS = 'TAKE_EXAM_FINISH_EXAM_SUCCESS';
