export const ADD_TODO = 'ADD_TODO';

// Login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

// Signup
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

// Logout
export const LOGOUT = 'LOGOUT';

// Modal
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

// Master table

export const MASTER_TABLE_FETCH_REQUEST = 'MASTER_TABLE_FETCH_REQUEST';
export const MASTER_TABLE_FETCH_SUCCESS = 'MASTER_TABLE_FETCH_SUCCESS';
export const MASTER_TABLE_FETCH_FAILURE = 'MASTER_TABLE_FETCH_FAILURE';

// Profile
export const PROFILE_FETCH_REQUEST = 'PROFILE_FETCH_REQUEST';
export const PROFILE_FETCH_SUCCESS = 'PROFILE_FETCH_SUCCESS';
export const PROFILE_FETCH_FAILURE = 'PROFILE_FETCH_FAILURE';
export const PROFILE_UPDATE_REQUEST = 'PROFILE_UPDATE_REQUEST';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const PROFILE_UPDATE_FAILURE = 'PROFILE_UPDATE_FAILURE';
export const PROFILE_DELETE_REQUEST = 'PROFILE_DELETE_REQUEST';
export const PROFILE_DELETE_SUCCESS = 'PROFILE_DELETE_SUCCESS';
export const PROFILE_DELETE_FAILURE = 'PROFILE_DELETE_FAILURE';
export const PROFILE_PICTURE_UPLOAD_REQUEST = 'PROFILE_PICTURE_UPLOAD_REQUEST';
export const PROFILE_PICTURE_UPLOAD_SUCCESS = 'PROFILE_PICTURE_UPLOAD_SUCCESS';
export const PROFILE_PICTURE_UPLOAD_FAILURE = 'PROFILE_PICTURE_UPLOAD_FAILURE';

// Employee
export const EMPLOYEE_CREATE_REQUEST = 'EMPLOYEE_CREATE_REQUEST';
export const EMPLOYEE_CREATE_SUCCESS = 'EMPLOYEE_CREATE_SUCCESS';
export const EMPLOYEE_CREATE_FAILURE = 'EMPLOYEE_CREATE_FAILURE';
export const EMPLOYEE_FETCH_REQUEST = 'EMPLOYEE_FETCH_REQUEST';
export const EMPLOYEE_FETCH_SUCCESS = 'EMPLOYEE_FETCH_SUCCESS';
export const EMPLOYEE_FETCH_FAILURE = 'EMPLOYEE_FETCH_FAILURE';
export const FILTER_EMPLOYEE = 'FILTER_EMPLOYEE';

// Project
export const PROJECT_CREATE_REQUEST = 'PROJECT_CREATE_REQUEST';
export const PROJECT_CREATE_SUCCESS = 'PROJECT_CREATE_SUCCESS';
export const PROJECT_CREATE_FAILURE = 'PROJECT_CREATE_FAILURE';
export const PROJECT_FETCH_REQUEST = 'PROJECT_FETCH_REQUEST';
export const PROJECT_FETCH_SUCCESS = 'PROJECT_FETCH_SUCCESS';
export const PROJECT_FETCH_FAILURE = 'PROJECT_FETCH_FAILURE';
export const FILTER_PROJECT = 'FILTER_PROJECT';
export const SORT_PROJECT = 'SORT_PROJECT';

// Project detail
export const PROJECT_DETAIL_FETCH_REQUEST = 'PROJECT_DETAIL_FETCH_REQUEST';
export const PROJECT_DETAIL_FETCH_SUCCESS = 'PROJECT_DETAIL_FETCH_SUCCESS';
export const PROJECT_DETAIL_FETCH_FAILURE = 'PROJECT_DETAIL_FETCH_FAILURE';
export const PROJECT_DETAIL_UPDATE_REQUEST = 'PROJECT_DETAIL_UPDATE_REQUEST';
export const PROJECT_DETAIL_UPDATE_SUCCESS = 'PROJECT_DETAIL_UPDATE_SUCCESS';
export const PROJECT_DETAIL_UPDATE_FAILURE = 'PROJECT_DETAIL_UPDATE_FAILURE';
export const MEMBER_CREATE_REQUEST = 'MEMBER_CREATE_REQUEST';
export const MEMBER_CREATE_SUCCESS = 'MEMBER_CREATE_SUCCESS';
export const MEMBER_CREATE_FAILURE = 'MEMBER_CREATE_FAILURE';

// Leave
export const LEAVE_CREATE_REQUEST = 'LEAVE_CREATE_REQUEST';
export const LEAVE_CREATE_SUCCESS = 'LEAVE_CREATE_SUCCESS';
export const LEAVE_CREATE_FAILURE = 'LEAVE_CREATE_FAILURE';
export const LEAVE_FETCH_REQUEST = 'LEAVE_FETCH_REQUEST';
export const LEAVE_FETCH_SUCCESS = 'LEAVE_FETCH_SUCCESS';
export const LEAVE_FETCH_FAILURE = 'LEAVE_FETCH_FAILURE';
export const LEAVE_UPDATE_REQUEST = 'LEAVE_UPDATE_REQUEST';
export const LEAVE_UPDATE_SUCCESS = 'LEAVE_UPDATE_SUCCESS';
export const LEAVE_UPDATE_FAILURE = 'LEAVE_UPDATE_FAILURE';
export const FILTER_LEAVE = 'FILTER_LEAVE';

// Timesheet
export const TIMESHEET_CREATE_REQUEST = 'TIMESHEET_CREATE_REQUEST';
export const TIMESHEET_CREATE_SUCCESS = 'TIEMSHEET_CREATE_SUCCESS';
export const TIMESHEET_CREATE_FAILURE = 'TIMESHEET_CREATE_FAILURE';
export const TIMESHEET_FETCH_REQUEST = 'TIMESHEET_FETCH_REQUEST';
export const TIMESHHET_FETCH_SUCCESS = 'TIMESHHET_FETCH_SUCCESS';
export const TIMESHHET_FETCH_FAILURE = 'TIMESHHET_FETCH_FAILURE';
export const TIMESHEET_UPDATE_REQUEST = 'TIMESHEET_UPDATE_REQUEST';
export const TIMESHEET_UPDATE_SUCCESS = 'TIMESHEET_UPDATE_SUCCESS';
export const TIMESHEET_UPDATE_FAILURE = 'TIMESHEET_UPDATE_FAILURE';
export const TIMESHEET_DELETE_REQUEST = 'TIMESHEET_DELETE_REQUEST';
export const TIMESHEET_DELETE_SUCCESS = 'TIMESHEET_DELETE_SUCCESS';
export const TIMESHEET_DELETE_FAILURE = 'TIMESHEET_DELETE_FAILURE';
