// Profile
export const EDIT_GENERAL_PROFILE = 'EDIT_GENERAL_PROFILE';
export const EDIT_WORK_PROFILE = 'EDIT_WORK_PROFILE';
export const EDIT_EDUCATION_PROFILE = 'EDIT_EDUCATION_PROFILE';
export const EDIT_CERTIFICATION_PROFILE = 'EDIT_CERTIFICATION_PROFILE';
export const EDIT_ASSET_PROFILE = 'EDIT_ASSET_PROFILE';
export const ADD_EDUCATION_PROFILE = 'ADD_EDUCATION_PROFILE';
export const ADD_CERTIFICATE_PROFILE = 'ADD_CERTIFICATE_PROFILE';
export const ADD_ASSET_PROFILE = 'ADD_ASSET_PROFILE';
export const VIEW_PROFILE_PICTURE = 'VIEW_PROFILE_PICTURE';
export const EDIT_PROFILE_PICTURE = 'EDIT_PROFILE_PICTURE';

// Employee
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';

// Project
export const ADD_PROJECT = 'ADD_PROJECT';
export const EDIT_PROJECT = 'EDIT_PROJECT';
export const ADD_MEMBER = 'ADD_MEMBER';

// Leave
export const CREATE_LEAVE_REQUEST = 'CREATE_LEAVE_REQUEST';

// Timesheet
export const ADD_TIMESHEET = 'CREATE_TIMESHEET';
export const EDIT_TIMESHEET = 'EDIT_TIMESHEET';

// Other
export const CONFIRM = 'CONFIRM';
