// Profile
export const EDIT_GENERAL_PROFILE = 'EDIT_GENERAL_PROFILE';
export const EDIT_WORK_PROFILE = 'EDIT_WORK_PROFILE';
export const EDIT_EDUCATION_PROFILE = 'EDIT_EDUCATION_PROFILE';
export const EDIT_CERTIFICATION_PROFILE = 'EDIT_CERTIFICATION_PROFILE';
export const EDIT_ASSET_PROFILE = 'EDIT_ASSET_PROFILE';
export const ADD_EDUCATION_PROFILE = 'ADD_EDUCATION_PROFILE';
export const ADD_CERTIFICATE_PROFILE = 'ADD_CERTIFICATE_PROFILE';
export const ADD_ASSET_PROFILE = 'ADD_ASSET_PROFILE';
export const PROFILE_PICTURE = 'PROFILE_PICTURE';

// Employee
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';

// Project
export const ADD_PROJECT = 'ADD_PROJECT';

// Leave
export const CREATE_LEAVE_REQUEST = 'CREATE_LEAVE_REQUEST';

// Other
export const CONFIRM = 'CONFIRM';

// Exam
export const ADD_NEW_EXAM = 'ADD_NEW_EXAM';
export const EDIT_EXAM = 'EDIT_EXAM';
export const VIEW_EXAM = 'VIEW_EXAM';

// Recruitment
export const EDIT_RECRUITMENT = 'EDIT_RECRUITMENT';
export const ACTIVE_EXAM_USER = 'ACTIVE_EXAM_USER';
export const GRADING_EXAM = 'GRADING_EXAM';
