// Profile
export const EDIT_GENERAL_PROFILE = 'EDIT_GENERAL_PROFILE';
export const EDIT_WORK_PROFILE = 'EDIT_WORK_PROFILE';
export const EDIT_EDUCATION_PROFILE = 'EDIT_EDUCATION_PROFILE';
export const EDIT_CERTIFICATION_PROFILE = 'EDIT_CERTIFICATION_PROFILE';
export const EDIT_ASSET_PROFILE = 'EDIT_ASSET_PROFILE';
export const ADD_EDUCATION_PROFILE = 'ADD_EDUCATION_PROFILE';

// Employee
export const CREATE_EMPLOYEE = 'CREATE_EMPLOYEE';

// Project
export const ADD_PROJECT = 'ADD_PROJECT';

// Leave
export const CREATE_LEAVE_REQUEST = 'CREATE_LEAVE_REQUEST';
